### PR TITLE
framework: enable button backlights

### PR DESCRIPTION
**Pull request by mobspyguy**
Change-Id: I59391406097ab26488bfcae1434fe2665575928d

### CODE REVIEW

**Comment by micky387** [comment]
Where do you find this ?
doesnt exist in frameworks ....

**Comment by mobspyguy** [comment]
Firstly I saw this at RR-Devices repo and included to lineage-sdk but didn't work. Then I asked into RR maintainer thread at telegram, where I get the answer. After include to framework, button backlight works.

**Comment by micky387** [comment]
ok but we working on LineageOS repo. So all pull request are welcome but you have to be sure it works on LineageOS before. We cant add  more work that is not present inside,sorry.

**Comment by mobspyguy** [comment]
No problem. How you surely know, RR based on Lineage sources, so I thought it works on purely Lineage too. Before next pull request, I will check the compatibility.

**Pull request closed without merging**
